## Content
* [Dataset Generation](#1.0-Dataset-Generation)
* [Data Cleaning](#2.0-Data-Cleaning)
* [EDA](#3.0-EDA)

### 1.0 Dataset Generation

In [1]:
import pandas as pd

In [2]:
def combinations(original_list):
    # The number of subsets is 2^n
    num_subsets = 2 ** len(original_list)

    # Create an empty list to hold all the subsets
    subsets = []

    # Iterate over all possible subsets
    for subset_index in range(num_subsets):
        # Create an empty list to hold the current subset
        subset = []
        # Iterate over all elements in the original list
        for index in range(len(original_list)):
            # Check if index bit is set in subset_index
            if (subset_index & (1 << index)) != 0:
                # If the bit is set, add the element at this index to the current subset
                subset.append(original_list[index])
        # Add the current subset to the list of all subsets
        subsets.append(subset)
        
    return subsets

In [15]:
# Using the function to print generated combinations
lst = [12, 14, 15, 23, 24, 25, 26, 35, 36, 45, 47, 48, 56, 57, 58, 59, 68, 69, 78, 89]
all_combinations = pd.DataFrame (combinations(lst))
all_combinations.head (15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,12.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,12.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,14.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,12.0,14.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,12.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,14.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12.0,14.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,15.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,12.0,15.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14.0,15.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
len(all_combinations.index)

1048576

In [17]:
data_types = all_combinations.dtypes

print(data_types)

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
dtype: object

### 2.0 Data Cleaning

In [18]:
#remove first row 
all_combinations_clean = all_combinations.tail(-1)
all_combinations_clean.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,12.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,12.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#rename columns 
all_combinations_clean.columns = ['VC1', 'VC2', 'VC3', 'VC4', 'VC5', 'VC6', 'VC7', 'VC8', 'VC9', 'VC10',
                            'VC11', 'VC12', 'VC13', 'VC14', 'VC15', 'VC16', 'VC17', 'VC18', 'VC19', 'VC20']
all_combinations_clean.head(5)

,VC1,VC2,VC3,VC4,VC5,VC6,VC7,VC8,VC9,VC10,VC11,VC12,VC13,VC14,VC15,VC16,VC17,VC18,VC19,VC20
1,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,12.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,12.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
all_combinations_clean.isnull().sum()

VC1           0
VC2          20
VC3         210
VC4        1350
VC5        6195
VC6       21699
VC7       60459
VC8      137979
VC9      263949
VC10     431909
VC11     616665
VC12     784625
VC13     910595
VC14     988115
VC15    1026875
VC16    1042379
VC17    1047224
VC18    1048364
VC19    1048554
VC20    1048574
dtype: int64

In [21]:
#drop columns without at least 4 VC
all_combinations_clean=all_combinations_clean.dropna(subset=["VC4"])
len(all_combinations_clean.index)

1047225

In [23]:
#replace Nan with 0 for readability
all_combinations_clean.fillna(0, inplace=True)
all_combinations_clean.head(5)

,VC1,VC2,VC3,VC4,VC5,VC6,VC7,VC8,VC9,VC10,VC11,VC12,VC13,VC14,VC15,VC16,VC17,VC18,VC19,VC20
15,12.0,14.0,15.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,12.0,14.0,15.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,12.0,14.0,23.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,12.0,15.0,23.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,14.0,15.0,23.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
#change datatype 
all_combinations_clean = all_combinations_clean.astype(int)
all_combinations_clean.head(5)

,VC1,VC2,VC3,VC4,VC5,VC6,VC7,VC8,VC9,VC10,VC11,VC12,VC13,VC14,VC15,VC16,VC17,VC18,VC19,VC20
15,12,14,15,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,12,14,15,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,12,14,23,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29,12,15,23,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
30,14,15,23,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [26]:
data_types = all_combinations_clean.dtypes
print(data_types)

VC1     int32
VC2     int32
VC3     int32
VC4     int32
VC5     int32
VC6     int32
VC7     int32
VC8     int32
VC9     int32
VC10    int32
VC11    int32
VC12    int32
VC13    int32
VC14    int32
VC15    int32
VC16    int32
VC17    int32
VC18    int32
VC19    int32
VC20    int32
dtype: object

In [29]:
#save cleaned df as csv
all_combinations_clean.to_csv("all_combinations.csv", index=False)

In [28]:
#save selection from cleaned df as csv
all_combinations_selection = all_combinations_clean.sample(n = 1000, random_state = 145, replace = False)
all_combinations_selection.to_csv("all_combinations_selection.csv", index=False)

### 3.0 EDA